### PR TITLE
Endpoint for conjugation of verb by pronoun and tense

### PR DESCRIPTION
**Pull request by jagatfx**
Adjusted the conjugate endpoint to conjugate a verb by pronoun and tense (using their names in the data files). 

To test:
- npm start
- open http://localhost:3001/api/conjugate/hacer?pronoun=yo&tense=imperfect%20subjunctive

### CODE REVIEW

**Comment by sdee** [comment]
http://localhost:3001/api/conjugate/hacer?pronoun=yo&tense=imperfect%20indicative results in an error. I'm okay with the fault being indicative, but I think adding indicative should work also. 

I also think that mood should be an explicit parameter ie mood=subjunctive.

**Comment by jagatfx** [comment]
@sdee 'imperfect indicative' is not in tenses.json, so the error is correct. If you want that supported, you should change tenses.json to the names you want. 

I'll add the mood parameter but it is completely redundant with the tense names listed in tenses.json. I think maybe you want to refactor your system of mood / tense.

**Comment by jagatfx** [comment]
```
  {
    "name": "present subjunctive",
    "abbr": "pass",
    "mood": "subjunctive"
  },
```

Also, this looks to be a bug since it does not follow the naming convention that indicative uses which would have the abbreviation pres. pass implies past subjunctive, given the previous naming.

**Comment by jagatfx** [comment]
@sdee why are there two imperfect subjunctive tenses? 

```
  {
    "name": "imperfect subjunctive",
    "abbr": "pass",
    "mood": "subjunctive"
  },
  {
    "name": "imperfect subjunctive 2",
    "abbr": "pass2",
    "mood": "subjunctive"
  },
```

Unless the name in tenses.json changes to something else, it is unclear what you want the mood parameter to do.

**Comment by sdee** [comment]
I was thinking about the API from an external perspective. If we keep it internal, we can use the tenses.json. I wasn't super happy with the compound tenses in tenses.json. We can revisit that decision after we get a 1.0 or whatever we call it.

The 'pass' is indeed a typo. Good catch. 

Spanish has two imperfect subjunctives. #1 is more common, #2 is used some in Spain. Both are implemented in the conjugation library: "pass" and "passb"

**Comment by sdee** [comment]
Could you fix the typo in tenses? Then, let's merge it in.

**Comment by jagatfx** [comment]
@sdee I think the name value in tenses.json is a great place to define the external name for tenses. So I think we should adjust to what the external value should be for the API. I'll make some proposed changes and check them in and you can let me know what you think.

**Comment by sdee** [comment]
Sounds good! It's good to do things more systematically before the code gets much bigger.

**Comment by jagatfx** [comment]
@sdee have another look with the latest changes. Now mood and tense are distinct but their definitions live together in the same data file with codes for each allowable combination. The API accepts the mood and tense values used in this file.

**Comment by sdee** [comment]
Looks good! +1

**Pull request merged**
