### PR TITLE
Added ability to go back with left key

### PR DESCRIPTION
**Pull request by jagatfx**
- Added a PREV_QUESTION redux action
- Added state tracking of the question sequence
- Updated NEXT_QUESTION redux action to function as redo when on an older question

I decided against using redux-undo because we don't want all the state to revert. Better to be able to select what happens and how to track changes over time. This will be useful for scoring as well. I did test out the redux-undo and it worked as expected. Package still included as a dependency since I think it will be useful for other things.

### CODE REVIEW

**Comment by sdee** [comment]
+1. I changed the comments a little to fix a typo and make them a little more explanatory.

Not the fault of this commit, but it seems like the state object is getting a little unwieldy. Do we have to make it flat like that or can we organize it by question, state, and the overall state of the quiz?

**Comment by sdee** [comment]
Forgot ... don't we want a back button? Or do you think this feature won't be used very often?

**Comment by jagatfx** [comment]
@sdee You can reorganize the state however you want. It does not have to stay the way it is.

**Comment by jagatfx** [comment]
@sdee re: the back button, feel free to add it.

**Pull request merged**
